version: "3.9"

services:
  influxdb_jmeter:
    image: influxdb:1.8.10
    container_name: influxdb_jmeter
    ports:
      - "8777:8086"
    environment:
      - INFLUXDB_DB=Integrate_jmeter
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin_password
      - INFLUXDB_USER=jmeter
      - INFLUXDB_USER_PASSWORD=jmeter_password
    volumes:
      - influxdb-data-jmeter:/var/lib/influxdb

  influxdb_jmeter_tcp:
    image: influxdb:1.8.10
    container_name: influxdb_jmeter_tcp
    ports:
      - "8778:8086"
    environment:
      - INFLUXDB_DB=Integrate_jmeter_tcp
      - INFLUXDB_ADMIN_USER=admin_tcp
      - INFLUXDB_ADMIN_PASSWORD=admin_password_tcp
      - INFLUXDB_USER=jmeter_tcp
      - INFLUXDB_USER_PASSWORD=jmeter_password_tcp
    volumes:
      - influxdb-data-jmeter-tcp:/var/lib/influxdb

  influxdb_jmeter_hc:
    image: influxdb:1.8.10
    container_name: influxdb_jmeter_hc
    ports:
      - "8779:8086"
    environment:
      - INFLUXDB_DB=Integrate_jmeter_hc
      - INFLUXDB_ADMIN_USER=admin_hc
      - INFLUXDB_ADMIN_PASSWORD=admin_password_hc
      - INFLUXDB_USER=jmeter_hc
      - INFLUXDB_USER_PASSWORD=jmeter_password_hc
    volumes:
      - influxdb-data-jmeter-hc:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3777:3000"
    depends_on:
      - influxdb_jmeter
      - influxdb_jmeter_tcp
      - influxdb_jmeter_hc
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/letsencrypt/live/3c16t1t8l22k0u8p15b17k0z21p19h22l3t16k22u8p15t27.com/fullchain.pem
      - GF_SERVER_CERT_KEY=/etc/letsencrypt/live/3c16t1t8l22k0u8p15b17k0z21p19h22l3t16k22u8p15t27.com/privkey.pem
    user: root
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini

  nextjs_app:
    image: node:18-alpine
    container_name: nextjs_app
    ports:
      - "3776:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3776
    depends_on:
      - influxdb_jmeter
      - grafana

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/log:/var/log/nginx
    depends_on:
      - nextjs_app

volumes:
  influxdb-data-jmeter:
  influxdb-data-jmeter-tcp:
  influxdb-data-jmeter-hc:
  grafana-data:
