apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb_jmeter:8086
    database: Integrate_jmeter
    user: jmeter
    password: jmeter_password
    isDefault: true
    jsonData:
      httpMode: POST

  - name: InfluxDB_TCP
    type: influxdb
    access: proxy
    url: http://influxdb_jmeter_tcp:8086
    database: Integrate_jmeter_tcp
    user: jmeter_tcp
    password: jmeter_password_tcp
    isDefault: false
    jsonData:
      httpMode: POST

  - name: InfluxDB_HC
    type: influxdb
    access: proxy
    url: http://influxdb_jmeter_hc:8086
    database: Integrate_jmeter_hc
    user: jmeter_hc
    password: jmeter_password_hc
    isDefault: false
    jsonData:
      httpMode: POST
