import "./globals.css";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <>
      <h2>HomePage</h2>
    </>
  );
}
